BASIC OPERATIONS

In [ ]:
import numpy as np
a1=np.array([1,3,4])
a2=np.array([5,6,3])
print(a1**2)
print(a1+a2)
print(a2-a1)
print(a1*a2)
print(a1/a2)
print(a1.dot(a2))
print(np.sqrt(a1))
print(np.std(a2))

[ 1  9 16]
[6 9 7]
[ 4  3 -1]
[ 5 18 12]
[0.2        0.5        1.33333333]
35
[1.         1.73205081 2.        ]
1.247219128924647


DIMENTIONS

In [ ]:
import numpy as np
a=np.array([1,3,4])
b=np.array([[1,3],[2,4],[6,7]])
print(a)
print(np.ndim(a))
print('dimensions:',np.ndim(b))

[1 3 4]
1
dimensions: 2


DATA TYPE / SIZE / SHAPE

In [ ]:
import numpy as np
a=np.array([[1,3],[2,4],[6,7]])
print(a)
print('data type:',a.dtype)    #shows datatype
b=a.astype(float)      #typecasting
print(b)
print('data type after:',b.dtype)
print('size of element:',a.itemsize,"Bits")
print('size of array:',a.size)
print('shape:',a.shape)
print(a.reshape(2,3))
print(a.reshape(6,1))

[[1 3]
 [2 4]
 [6 7]]
data type: int64
[[1. 3.]
 [2. 4.]
 [6. 7.]]
data type after: float64
size of element: 8 Bits
size of array: 6
shape: (3, 2)
[[1 3 2]
 [4 6 7]]
[[1]
 [3]
 [2]
 [4]
 [6]
 [7]]
