HANDLE MISSING VALUES

In [ ]:
import numpy as np
a=np.array([1,2,np.nan,3,4,np.nan,5])
print(np.isnan(a)) #shows true for nan values
print(np.nan==np.nan) #cannot be compared
r=np.nan_to_num(a)   #by default replaces by zero
print(r)
r=np.nan_to_num(a,nan=100)
print(r)

[False False  True False False  True False]
False
[1. 2. 0. 3. 4. 0. 5.]
[  1.   2. 100.   3.   4. 100.   5.]


HANDLE INFINITE VALUES

In [ ]:
import numpy as np
a=np.array([1,2,np.inf,3,4,-np.inf,5])
print(np.isinf(a))
#posinf = +ve infinity and neginf = -ve infinity
cleaned_array=np.nan_to_num(a,posinf=100,neginf=-100)
print(cleaned_array)

[False False  True False False  True False]
[   1.    2.  100.    3.    4. -100.    5.]


In [1]:
import numpy as np
a=np.array([1,2,np.inf,3,4,-np.inf,5])
print(np.isinf(a))
#posinf = +ve infinity and neginf = -ve infinity
cleaned_array=np.nan_to_num(a,posinf=100,neginf=-100)
print(cleaned_array)

[False False  True False False  True False]
[   1.    2.  100.    3.    4. -100.    5.]
