CONCATENATION

In [ ]:
import numpy as np
a1=np.array([1,3,4])
a2=np.array([5,6,7])
np.concatenate([a1,a2])

ARANGE FUNCTION

In [ ]:
l=range(5)
print(l)
print(l[2])
a=np.array([1,2,3,4,5,6])
print(a[0:3])
print(a[-1])
print(np.arange(1,5))
print(np.arange(1,6,2))

range(0, 5)
2
[1 2 3]
6
[1 2 3 4]
[1 3 5]


LINSPACE FUNCTION

In [ ]:
import numpy as np
np.linspace(1,4,9)  #generates 9 no. btw 1-4

RAVEL / FLATEN FUNCTION

In [ ]:
import numpy as np
a=np.array([[1,3],[2,4],[6,7]])
print(a)
#view
print(a.ravel())
print(a.flatten())

[[1 3]
 [2 4]
 [6 7]]
[1 3 2 4 6 7]
[1 3 2 4 6 7]


NDITER FUNCTION

In [ ]:
import numpy as np
a=np.arange(12).reshape(3,4)
print(a)
print()
#iterate elements column vise
for x in np.nditer(a,order='F'):#F stands for fortran
  print(x,end=" ")
print()
#transpose column into raws and rows into columns
for x in np.nditer(a,order='F',flags=['external_loop']):
  print(x)
print()
for x in np.nditer(a,op_flags=['readwrite']):
  x[...]=x*x
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

0 4 8 1 5 9 2 6 10 3 7 11 
[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [ ]:
import numpy as np
a=np.array([1,2,np.inf,3,4,-np.inf,5])
print(np.isinf(a))