CREATE MATRIX

In [ ]:
import numpy as np
a=np.zeros((3,4))
print(a)
print()
a=np.ones((3,4))
print(a)
print()
a=np.full((2,3),7)
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[7 7 7]
 [7 7 7]]


SLICING

In [ ]:
import numpy as np
a=np.array([[1,3,4],[2,4,5],[6,7,8]])
print(a)
print(a[1,2])
print(a[-1])
print(a[-1,0:2])
print(a[:,1:3])

[[1 3 4]
 [2 4 5]
 [6 7 8]]
5
[6 7 8]
[6 7]
[[3 4]
 [4 5]
 [7 8]]


INSERTION / DELETION

In [ ]:
import numpy as np
a=np.array([[1,3,4],[2,4,5],[6,7,8]])
print(a)
a=np.insert(a,1,[5,6,7],axis=1)
print(a)
print(np.append(a,[9,9,9]))
print(np.delete(a,1))

[[1 3 4]
 [2 4 5]
 [6 7 8]]
[[1 5 3 4]
 [2 6 4 5]
 [6 7 7 8]]
[1 5 3 4 2 6 4 5 6 7 7 8 9 9 9]
[1 3 4 2 6 4 5 6 7 7 8]


ACESSING ELEMENTS

In [ ]:
import numpy as np
a=np.array([[1,3,4],[2,4,5],[6,7,8]])
for row in a:
  print(row)
for cell in a.flat:
  print(cell)

[1 3 4]
[2 4 5]
[6 7 8]
1
3
4
2
4
5
6
7
8
